name: infoklub
description: "All Info in a single place"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.8.1

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  country_picker: ^2.0.27
  country_pickers: ^3.0.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  pdf: ^3.11.3
  open_file: ^3.5.10
  fluttertoast: ^8.2.12
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  hive: ^2.2.3
  flutter_secure_storage: ^9.0.0
  file_picker: ^10.2.0
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  day_night_time_picker: ^1.3.1
  syncfusion_flutter_datepicker: ^30.2.5
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  awesome_notifications: ^0.10.1
  permission_handler: ^12.0.1
  flutter_launcher_icons: ^0.14.4 
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_native_splash: ^2.3.1

# flutter launcher icons
flutter_launcher_icons:
  android: true 
  ios: true
  image_path: "lib/assets/icon/infoKlubLogo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/icon/infoKlubLogo.png"
 


# flutter nayive splash
flutter_native_splash:
  color: "#ffffff"
  android: true
  ios: true
  web: false
  android_gravity: center



flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/Images/
    - lib/assets/cv_tem/
    - lib/assets/icon/


