// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMRtHQcpHlW9NDvYjeJjbNfVqIZUYsGD4',
    appId: '1:588343803358:web:f3e31717b10d2c14a8f14f',
    messagingSenderId: '588343803358',
    projectId: 'info-klub',
    authDomain: 'info-klub.firebaseapp.com',
    storageBucket: 'info-klub.firebasestorage.app',
    measurementId: 'G-3YL9SH8R9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR2AMFSOHeYFafzyu9CJdVUFGVjxMP9kc',
    appId: '1:588343803358:android:385f13d8027988b3a8f14f',
    messagingSenderId: '588343803358',
    projectId: 'info-klub',
    storageBucket: 'info-klub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAukzbQF22K-0I3KeoVeMLMletvlhyZx8k',
    appId: '1:588343803358:ios:d02dc203cef824eca8f14f',
    messagingSenderId: '588343803358',
    projectId: 'info-klub',
    storageBucket: 'info-klub.firebasestorage.app',
    iosBundleId: 'com.example.infoklub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAukzbQF22K-0I3KeoVeMLMletvlhyZx8k',
    appId: '1:588343803358:ios:d02dc203cef824eca8f14f',
    messagingSenderId: '588343803358',
    projectId: 'info-klub',
    storageBucket: 'info-klub.firebasestorage.app',
    iosBundleId: 'com.example.infoklub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMRtHQcpHlW9NDvYjeJjbNfVqIZUYsGD4',
    appId: '1:588343803358:web:88d6a705db26aefba8f14f',
    messagingSenderId: '588343803358',
    projectId: 'info-klub',
    authDomain: 'info-klub.firebaseapp.com',
    storageBucket: 'info-klub.firebasestorage.app',
    measurementId: 'G-WTR3677G9E',
  );
}
